runtime: nodejs20
env: standard

instance_class: F1 # Optional: Choose an appropriate instance class

automatic_scaling:
  max_instances: 3 # Maximum number of instances to run

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301

  # Handler for API requests
  - url: /api/.*

  # Handler for static files in the root folder
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html

  # Handler for other static files
  - url: /.*
    static_dir: client/build