runtime: nodejs20
env: standard

instance_class: F2

automatic_scaling:
  min_idle_instances: 1
  max_instances: 3

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /api/.*
    script: auto

  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    secure: always
    redirect_http_response_code: 301
    static_files: client/build/\1
    upload: client/build/(.*\..+)$


  # Serve index.html for all other requests for client-side routing
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: client/build/index.html
    upload: client/build/index.html

#    old config
#
#  - url: /
#    secure: always
#    redirect_http_response_code: 301
#    static_files: client/build/index.html
#    upload: client/build/index.html
#
#  - url: /(.*)
#    secure: always
#    redirect_http_response_code: 301
#    static_files: client/build/\1
#    upload: client/build/(.*)
