runtime: nodejs20
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1  # Ensure at least 1 instance is always running
  min_idle_instances: 1  # Keep additional instances on standby
  max_instances: 3

env_variables:
  NODE_ENV: 'production'

handlers:
  # Serve API calls to the Node.js server
  - url: /api/.*
    script: auto

  # Serve editor static files with url ending with a file extension
  - url: /editor/(.*\..+)$
    static_files: admin-client/build/\1
    upload: admin-client/build/(.*\..+)$
    secure: always
    redirect_http_response_code: 301

  # serve editor index.html for all other requests for client-side routing
  - url: /editor/.*
    static_files: admin-client/build/index.html
    upload: admin-client/build/index.html
    secure: always
    redirect_http_response_code: 301


  # Serve web frontend static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: client/build/\1
    upload: client/build/(.*\..+)$
    secure: always
    redirect_http_response_code: 301

  # Serve web frontend index.html for all other requests for client-side routing
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: client/build/index.html
    upload: client/build/index.html
