runtime: nodejs20
env: standard

instance_class: F1 # Optional: Choose an appropriate instance class

automatic_scaling:
  max_instances: 3 # Maximum number of instances to run

# These handlers are mostly for efficiency only. They can be processed directly
# instead of redirecting the request to our nodejs app
handlers:
  # HTTP to HTTPS redirection
  - url: /.*
    secure: always
    redirect_http_response_code: 301

  # Handler for static files in the root folder
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html

  # Handler for other static files
  - url: /(.*\.(json|ico|js|png|jpg|css|txt|svg|woff|woff2|ttf|map))
    static_files: client/build/\1
    upload: client/build/.*\.(json|ico|js|png|jpg|css|txt|svg|woff|woff2|ttf|map)