name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          # allows gcloud to read credentials
          export_default_credentials: true
#      - name: Use Node.js 20.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#      - name: Compiling typescript
#        run: npm ci
#        working-directory: src/api
#      - run: npm run build
#        working-directory: src/api
      - name: Deploy to Google App Engine
        run: gcloud app deploy
        working-directory: src/api

