name: Production Pipeline (github-hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # even numbers are LTS releases
        node-version: [16, 18, 20]

    steps:
      # equivalent of doing git clone
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        # ensures node.js is available
        uses: actions/setup-node@v3
        with:
          # reference different versions
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # npm ci is equivalent to npm install but is specifically optimized for CI
      - run: npm ci
        working-directory: src
      - run: npm run build
        working-directory: src


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # even numbers are LTS releases
        node-version: [16, 18, 20]

    steps:
      # equivalent of doing git clone
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        # ensures node.js is available
        uses: actions/setup-node@v3
        with:
          # reference different versions
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      # npm ci is equivalent to npm install but is specifically optimized for CI
      - run: npm ci
        working-directory: src
      - run: npm test
        working-directory: src

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Google SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_SKOGKURS }}
          service_account_key: ${{ secrets.GCP_SA_KEY_SKOGKURS }}
          # allows gcloud to read credentials
          export_default_credentials: true
      - name: Installing dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        working-directory: src
      - run: npm run build
        working-directory: src
      - name: Deploy to Google App Engine
        run: gcloud app deploy
        working-directory: src

  backup:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to NTNU GitLab Workspace
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN}}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.stud.idi.ntnu.no/oysteinq/skogkurskalk.git"
          git fetch --prune --unshallow
          git push --force gitlab --all